nodeLinker: node-modules

# npmRegistryServer: "https://registry.yarnpkg.com"
# Commented out local Verdaccio registry to avoid accidental installs/publishes
# npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - localhost
