storage: /verdaccio/storage

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    allow_empty_password: true

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $all
    publish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: false

logs:
  - {type: stdout, format: pretty, level: http}

# Allow overwriting same version for local staging
allow_overwrite: true
